#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
#PS1='\[\e[33;40m\] \w \$\[\e[00m\] '
PS1=' \w \$ '

alias l="ls -al"
alias sudo="sudo -E"


# for tmux: export 256color
[ -n "$TMUX" ] && export TERM=screen-256color
